### ISSUE TITLE
Use gas oracle to avoid super expensive tend operations

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#1]
https://github.com/Schlagonia/liquity-stability-pool-strat/blob/3da330548c7e7abb481cea1f33f16688ea4b478b/contracts/Strategy.sol#L608-L621

Maybe checking the current base fee would be a good idea to avoid calling `tend()` with insane gas prices. Not sure on what most recent strategies are using for this but you can find an example here:

https://github.com/therealmonoloco/maker-dai-delegate/blob/main/contracts/Strategy.sol#L53-L54
https://github.com/therealmonoloco/maker-dai-delegate/blob/main/contracts/Strategy.sol#L485
https://github.com/therealmonoloco/maker-dai-delegate/blob/main/contracts/Strategy.sol#L776-L789

**Comment by Schlagonia** [comment]
updated 9f7f1fd9ad4a11a8e93c3657142813a04033000f
