### ISSUE TITLE
Check there is at least amount DAI in balance

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#2]
https://github.com/Schlagonia/liquity-stability-pool-strat/blob/3da330548c7e7abb481cea1f33f16688ea4b478b/contracts/Strategy.sol#L511

Ensure there is at least `_amount` to avoid reverts down the road.

**Comment by Schlagonia** [comment]
fixed https://github.com/Schlagonia/liquity-stability-pool-strat/commit/19e4d59b196f0609207f9dc0e485c68c6da34cd6
