### ISSUE TITLE
Is there any alternative to reporting a loss with enough DAI?

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#3]
https://github.com/Schlagonia/liquity-stability-pool-strat/blob/3da330548c7e7abb481cea1f33f16688ea4b478b/contracts/Strategy.sol#L293-L296

This would only apply to scenarios where a lot of balance is in DAI and still not converted to LUSD. Large withdrawals could mess up accounting due to the strategy reporting big losses and users receiving less than what they put in.

I would add an extra check and maybe revert if this is the case. This should be temporary anyway but better safe than sorry.

**Comment by Schlagonia** [comment]
fixed https://github.com/Schlagonia/liquity-stability-pool-strat/commit/19e4d59b196f0609207f9dc0e485c68c6da34cd6
