### ISSUE TITLE
Remove keeper tip

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#4]
Yearn strategies work with the kp3r network and as far as I know credits are managed independently of the strategy's balance. In this case it is being paid for with user funds.

I would remove all tip calculations from the strategy to keep it simpler.

**Comment by Schlagonia** [comment]
I have created a new branch without the tip https://github.com/Schlagonia/liquity-stability-pool-strat/tree/noTip

**Comment by Schlagonia** [comment]
Tip has been removed 42e76e0287a2571f4b9c0582c5f12ca9d27d9dd4
