### ISSUE TITLE
Refactor to avoid curve/uniswap swap duplication

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#5]
https://github.com/Schlagonia/liquity-stability-pool-strat/blob/3da330548c7e7abb481cea1f33f16688ea4b478b/contracts/Strategy.sol#L467-L555

Refactor `_sellDAIforLUSDonCurve()` and `_sellDAIforLUSDonUniswap()` to pass full balance as `_amount` to `_swapDaiAmountToLusd` and relevant functions to avoid repeating code. Rationale for this is to make it simpler to review and make sure the strategy is always swapping with the same parameters set.

**Comment by Schlagonia** [comment]
fixed https://github.com/Schlagonia/liquity-stability-pool-strat/commit/19e4d59b196f0609207f9dc0e485c68c6da34cd6
