### ISSUE TITLE
Refactor _sellETHforDAI and claimAndSellEth to avoid duplicating uniswap convert code

### ISSUE THREAD

**Issue by therealmonoloco** [Schlagonia/liquity-stability-pool-strat#6]
https://github.com/Schlagonia/liquity-stability-pool-strat/blob/3da330548c7e7abb481cea1f33f16688ea4b478b/contracts/Strategy.sol#L576-L600

`claimAndSellEth` and `_sellETHforDAI` should be grouped to avoid code repetition and ensuring that ETH->DAI happens in a single, expected way.

**Comment by Schlagonia** [comment]
fixed https://github.com/Schlagonia/liquity-stability-pool-strat/commit/19e4d59b196f0609207f9dc0e485c68c6da34cd6
